export const SET_ARTICLES = 'SET_ARTICLES',
  FETCH_ARTICLES_START = 'FETCH_ARTICLES_START',
  FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE',
  SET_ACTIVE_ARTICLE = 'SET_ACTIVE_ARTICLE';
